* Updated the Dockerfile and entrypoint script 'start' for the SnappyData's docker image.

diff --git a/docker/start b/docker/start
--- a/docker/start
+++ b/docker/start
@@ -21,44 +21,121 @@ echo "$(id -u):x:$(id -u):$(id -g):dynamic uid:/opt/snappydata:/bin/false" >> /t
 
 export NSS_WRAPPER_PASSWD=/tmp/passwd
 export NSS_WRAPPER_GROUP=/etc/group
-export LD_PRELOAD=/usr/lib64/libnss_wrapper.so
+# export LD_PRELOAD=/usr/lib64/libnss_wrapper.so
 
-echo "starting sshd service"
+echo "Starting sshd service"
 service sshd start
 
 HOSTNAME=`hostname`
+PRODUCT_DIR=/opt/snappydata
+WORK_DIR="$PRODUCT_DIR/work/$HOSTNAME"
+mkdir -p "$WORK_DIR"
+HOSTNAME_FOR_CLIENTS=""
 
-IP=`ping -c 1 $HOSTNAME | grep "64 bytes from"|awk '{print $5}' | awk -F"(" '{print $2}' | awk -F")" '{print $1}'`
-sbin=/opt/snappydata/sbin
 die() { echo "ERROR: $*" 1>&2; exit 1; }
 
+getServiceIP() {
+    KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
+    KUBE_CACERT="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
+    CURRENT_NAMESPACE=`cat /var/run/secrets/kubernetes.io/serviceaccount/namespace`
+    KUBE_API_URL="https://kubernetes.default.svc.cluster.local/api/v1/namespaces/$CURRENT_NAMESPACE/services/$1"
+    SERVICE_IP=""
+    wget -O service -q --ca-certificate $KUBE_CACERT  --header "Authorization: Bearer $KUBE_TOKEN" ${KUBE_API_URL}
+    if [ $? != 0 ]; then
+      echo "ERROR: The service $1 is not found."
+    else
+      wget -O- -q --ca-certificate $KUBE_CACERT  --header "Authorization: Bearer $KUBE_TOKEN" ${KUBE_API_URL} | grep Forbidden
+      if [ $? == 0 ]; then
+        echo "ERROR: The current service-account does not have permission to list services."
+      else
+        success=1
+        counter=1
+        echo "Retrieving IP for $1 service ..."
+        while [ ${success} != 0 -a ${counter} -le 60 ]
+        do
+          sleep 2s
+          SERVICE_IP=`wget -O- -q --ca-certificate $KUBE_CACERT  --header "Authorization: Bearer $KUBE_TOKEN" ${KUBE_API_URL} | grep ip | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"`
+          success=$?
+          let counter=counter+1
+        done
+        if [ -z ${SERVICE_IP} ]; then
+           echo "Could not get IP for service $1"
+        else
+           echo "Retrieved IP ${SERVICE_IP} for $1 service."
+        fi
+      fi
+    fi
+}
 
+waitFor() {
+  COUNTER=0;
+  while ! nc -z $1 $2 > /dev/null 2>&1; do
+    echo "Waiting for $1 to be online ..."
+    sleep 5
+    let COUNTER=COUNTER+1
+    if [ ${COUNTER} -eq 50 ]; then
+      echo "ERROR: $1 is not up."
+      exit 1
+    fi
+  done
+  echo "Found service $1 listening on port $2."
+}
 
-case "$1" in
+PROCESS_NAME=$1
+
+while (( "$#" )); do
+  case "$2" in
+    --wait-for)
+      shift
+      waitFor $2 $3
+      shift 2
+    ;;
+    --get-ip)
+      shift
+      getServiceIP $2
+      shift
+    ;;
+    *)
+      break
+    ;;
+  esac
+done
+
+shift
+
+case "$PROCESS_NAME" in
    "")
-      echo "Usage: start [server|lead|locator|all]"
+      echo "Usage: start (locator|server|lead|all) [--get-ip service-name] [--wait-for service-name service-port] [<snappy-config> ...]"
       exit 1
       ;;
-   server)
-      echo $IP > /opt/snappydata/conf/servers
-      $sbin/snappy-servers.sh start "${@:2}"
-      ;;
    locator)
-      echo $IP > /opt/snappydata/conf/locators
-      sbin/snappy-locators.sh start "${@:2}"
+      if [ ! -z ${SERVICE_IP} ]; then
+        HOSTNAME_FOR_CLIENTS="-hostname-for-clients=$SERVICE_IP"
+      fi
+      echo "$HOSTNAME -dir=$WORK_DIR $@ $HOSTNAME_FOR_CLIENTS" > ${PRODUCT_DIR}/conf/locators
+      ${PRODUCT_DIR}/sbin/snappy-locators.sh start
+      ;;
+   server)
+      if [ ! -z ${SERVICE_IP} ]; then
+        HOSTNAME_FOR_CLIENTS="-hostname-for-clients=$SERVICE_IP"
+      fi
+      echo "$HOSTNAME -dir=$WORK_DIR $@ $HOSTNAME_FOR_CLIENTS" > ${PRODUCT_DIR}/conf/servers
+      ${PRODUCT_DIR}/sbin/snappy-servers.sh start
       ;;
    lead)
-      echo $IP > /opt/snappydata/conf/leads
-      $sbin/snappy-leads.sh start "${@:2}"
+      if [ ! -z ${SERVICE_IP} ]; then
+        echo "SPARK_PUBLIC_DNS=$SERVICE_IP" >> ${PRODUCT_DIR}/conf/spark-env.sh
+      fi
+      echo "$HOSTNAME -dir=$WORK_DIR $@" > ${PRODUCT_DIR}/conf/leads
+      ${PRODUCT_DIR}/sbin/snappy-leads.sh start
       ;;
    all)
-      $sbin/snappy-start-all.sh -client-bind-address=0.0.0.0 -prefer-netserver-ipaddress=true "${@:2}"
+      ${PRODUCT_DIR}/sbin/snappy-start-all.sh -client-bind-address=0.0.0.0 -prefer-netserver-ipaddress=true "$@"
       ;;
    * )
-   echo "Usage: start [server|lead|locator|all]"
+   echo "Usage: start (locator|server|lead|all) [--get-ip service-name] [--wait-for service-name service-port] [<snappy-config> ...]"
    die "Invalid Argument"
 esac
 
 
 tail -f /dev/null
-
