SNAP-2281 Fix member logs links on Pulse Dashboard (#8)
* Wait until lead service is initialized and assigned a public IP.
* Set SPARK_PUBLIC_DNS to above IP in lead container's spark-env.sh
* Moved scripting logic to start script.
* Download the start script used as entry point into the container from GH.

diff --git a/docker/start b/docker/start
--- a/docker/start
+++ b/docker/start
@@ -23,39 +23,71 @@ export NSS_WRAPPER_PASSWD=/tmp/passwd
 export NSS_WRAPPER_GROUP=/etc/group
 export LD_PRELOAD=/usr/lib64/libnss_wrapper.so
 
-echo "starting sshd service"
+echo "Starting sshd service"
 service sshd start
 
 HOSTNAME=`hostname`
+PRODUCT_DIR=/opt/snappydata
+WORK_DIR="$PRODUCT_DIR/work/$HOSTNAME"
+mkdir -p "$WORK_DIR"
 
-IP=`ping -c 1 $HOSTNAME | grep "64 bytes from"|awk '{print $5}' | awk -F"(" '{print $2}' | awk -F")" '{print $1}'`
-sbin=/opt/snappydata/sbin
 die() { echo "ERROR: $*" 1>&2; exit 1; }
-
 
 
 case "$1" in
    "")
-      echo "Usage: start [server|lead|locator|all]"
+      echo "Usage: start (locator|server|lead|all) [extra config]"
       exit 1
       ;;
-   server)
-      echo $IP "${@:2}" > /opt/snappydata/conf/servers
-      $sbin/snappy-servers.sh start
-      ;;
    locator)
-      echo $IP "${@:2}" > /opt/snappydata/conf/locators
-      sbin/snappy-locators.sh start
+      echo "$HOSTNAME -dir=$WORK_DIR ${@:2}" > ${PRODUCT_DIR}/conf/locators
+      ${PRODUCT_DIR}/sbin/snappy-locators.sh start
+      ;;
+   server)
+      COUNTER=0;
+      while ! nc -z snappydata-locator-internal 10334 > /dev/null 2>&1; do
+        echo "Waiting for locator to be online"
+        sleep 5
+        let COUNTER=COUNTER+1
+        if [ ${COUNTER} -eq 50 ]; then
+          echo "ERROR: Locator is not up"
+          exit 1
+        fi
+      done
+      echo "$HOSTNAME -dir=$WORK_DIR ${@:2}" > ${PRODUCT_DIR}/conf/servers
+      ${PRODUCT_DIR}/sbin/snappy-servers.sh start
       ;;
    lead)
-      echo $IP "${@:2}" > /opt/snappydata/conf/leads
-      $sbin/snappy-leads.sh start
+      COUNTER=0;
+      while ! nc -z snappydata-server 1527 > /dev/null 2>&1; do
+        echo "Waiting for servers to be online"
+        sleep 5
+        let COUNTER=COUNTER+1
+        if [ ${COUNTER} -eq 50 ]; then
+          echo "ERROR: Servers are not up"
+          exit 1
+        fi
+      done
+      KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
+      KUBE_CACERT="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
+      KUBE_API_URL="https://kubernetes/api/v1/namespaces/default/services/snappydata-leader/status"
+      success=1
+      while [ ${success} != 0 ]
+      do
+        sleep 3s
+        SERVICE_IP=`wget -O- -q --ca-certificate $KUBE_CACERT  --header "Authorization: Bearer $KUBE_TOKEN" ${KUBE_API_URL} | grep ip | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"`
+        success=$?
+      done
+      echo "Retrieved IP for service: ${SERVICE_IP}"
+      echo "SPARK_PUBLIC_DNS=$SERVICE_IP" >> ${PRODUCT_DIR}/conf/spark-env.sh
+      echo "$HOSTNAME -dir=$WORK_DIR ${@:2}" > ${PRODUCT_DIR}/conf/leads
+      ${PRODUCT_DIR}/sbin/snappy-leads.sh start
       ;;
    all)
-      $sbin/snappy-start-all.sh -client-bind-address=0.0.0.0 -prefer-netserver-ipaddress=true "${@:2}"
+      ${PRODUCT_DIR}/sbin/snappy-start-all.sh -client-bind-address=0.0.0.0 -prefer-netserver-ipaddress=true "${@:2}"
       ;;
    * )
-   echo "Usage: start [server|lead|locator|all]"
+   echo "Usage: start [locator|server|lead|all]"
    die "Invalid Argument"
 esac
 
